# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

services:
  airbyte-control-plane:
    image: kindest/node:v1.29.10
    container_name: airbyte-abctl-control-plane
    restart: always
    ports:
      - "56503:6443"
      - "8000:80"

  metabase:
    image: metabase/metabase
    container_name: metabase
    restart: always
    ports:
      - "3000:3000"
